# Public headers.
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

liba{isocline}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
liba{isocline}: h{*} h{*.c -isocline.c} c{isocline}

# Build options.
#
src_pfx_inc = [dir_path] $src_root/include/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$src_pfx_src" "-I$src_pfx_inc"

# {hbmia obja}{*}: c.poptions += -DLIBISOCLINE_STATIC_BUILD
# {hbmis objs}{*}: c.poptions += -DLIBISOCLINE_SHARED_BUILD

# Export options.
#
liba{isocline}: c.export.poptions = "-I$src_pfx_inc"

# liba{isocline}: c.export.poptions += -DLIBISOCLINE_STATIC
# libs{isocline}: c.export.poptions += -DLIBISOCLINE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{isocline}: bin.lib.version = "-$version.project_id"
else
  liba{isocline}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
