# Public headers.
#
pub = [dir_path] ../include/
include $pub
pub_hdrs = $($pub/ pub_hdrs)

liba{isocline}: $pub/{$pub_hdrs}

# Private headers and sources
#
liba{isocline}: h{*} h{*.c -isocline.c} c{isocline}

# Build options
#
src_pfx_inc = [dir_path] $src_root/include/
src_pfx_src = [dir_path] $src_root/src/
c.poptions =+ "-I$src_pfx_src" "-I$src_pfx_inc"

# Export options.
#
liba{isocline}: c.export.poptions = "-I$src_pfx_inc"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{isocline}: bin.lib.version = "-$version.project_id"
else
  liba{isocline}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
